apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  # postgres
  DB_USER: cG9zdGdyZXM=
  # EstaeslaclavesecretisimadelabasedeDatos
  DB_PASSWORD: RXN0YWVzbGFjbGF2ZXNlY3JldGlzaW1hZGVsYWJhc2VkZURhdG9z